### ISSUE TITLE
help

### ISSUE THREAD

**Issue by SmellySteve** [bloxlink/Bloxlink#29]
how do i connect redis and rethink db.

the error is thjis:
Unable to connect to Database: Could not connect to rethinkdb:28015. Error: [Errno 8] nodename nor servname provided, or not known. Retrying with a different host
and it keeps sapmming. help please.

**Comment by xomien** [comment]
As per our README, we do not provide self-hosting help.

**Comment by SmellySteve** [comment]
please?
